# Generated by Django 4.1.7 on 2023-08-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('stage_index', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_children', to='app.stage')),
            ],
            options={
                'ordering': ['stage_index'],
            },
        ),
    ]
