# Generated by Django 4.1.7 on 2023-04-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_dependens_on_answer',
        ),
    ]
