# Generated by Django 4.1.7 on 2023-04-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_question_dependens_on_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_dependens_on_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.answer'),
        ),
    ]
