# Generated by Django 4.1.7 on 2023-04-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_answer_dependens_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_dependens_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.answer'),
        ),
    ]
