# Generated by Django 4.1.7 on 2023-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answer_answer_dependens_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
