# Generated by Django 4.1.7 on 2023-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_useraccount_user_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['stage_index']},
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
