# Generated by Django 4.1.7 on 2023-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_stage_options_stage_stage_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
