# Generated by Django 4.1.7 on 2023-05-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_dependens_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='app.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='stage_fit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.stage'),
        ),
    ]
