# Generated by Django 4.1.7 on 2023-06-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_answer_dependens_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question_idd',
        ),
    ]
