# Generated by Django 4.1.7 on 2023-06-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_question_id_answer_question_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_idd',
            new_name='questionIdd',
        ),
    ]
